### ISSUE TITLE
Silly question

### ISSUE THREAD

**Issue by lupomontero** [gmoura/github-stars#1]
Hi @gmoura,

Following up on our conversation... just wanted to add a _silly question_ 🙈

In the following line...

https://github.com/gmoura/github-stars/blob/e9be514e4d381dc294a412ae4e8af8fdd2d19a2b/javascript/components/StarsButtons.js#L33

... you declare a variable (`buttons`) using the `let` _keyword_. Could you back up the choice of using `let` over using `const` or a _legacy_ `var`?

**Comment by gmoura** [comment]
Hi @lupomontero,

I made a mistake (sorry 😥 ). In this case I never reassigned the value of **buttons**, I think  **const** fit better than **let** in this case.

**Comment by lupomontero** [comment]
Hahaha, no probs... that was a bit of nitpicking on my part... :neckbeard:

Overall the code looks good :wink:

While reading through the code I couldn't help but at least _raise_ [another issue](https://github.com/gmoura/github-stars/issues/2) 🤓
