### ISSUE TITLE
Avoid declaring functions inside loops

### ISSUE THREAD

**Issue by lupomontero** [gmoura/github-stars#2]
https://github.com/gmoura/github-stars/blob/e9be514e4d381dc294a412ae4e8af8fdd2d19a2b/javascript/components/StarsButtons.js#L35

This invocation to `addEventListener()`, happens inside a `loop` (provided by `Array.prototype.forEach`). This basically means that we will be creating a new function (an anonymous _arrow function_ in this case) for each item in the list, which is not optimal (🙊). How would you prevent (optimise) this?

**Comment by gmoura** [comment]
I love code review <3  

I just created a helper function, every click event I call this function, follow the commit: 0a8d45313d1e926fd78d5f69c84c03adb50835f1

**Comment by lupomontero** [comment]
Nice solution 😄!
